version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_pass
      POSTGRES_DB: nexus_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nexus_net

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - nexus_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - nexus_net

volumes:
  pgdata:

networks:
  nexus_net:
    driver: bridge
